apiVersion: 1

datasources:
- name: BigQ
  type: doitintl-bigquery-datasource
  access: proxy
  isDefault: true
  jsonData:
       authenticationType: jwt
       clientEmail: cloud-run-test-241704@appspot.gserviceaccount.com
       defaultProject: cloud-run-test-241704
       tokenUri: https://oauth2.googleapis.com/token
  secureJsonData:
       privateKey: |
          -----BEGIN PRIVATE KEY-----
         private key
          -----END PRIVATE KEY-----
  version: 2
  readOnly: false
